# -*- coding: utf-8 -*-
"""run_recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lvZAodAtR0yzqURjXOV9H0hYqhW-TP6w
"""

import argparse
from face_recognition.recognition import recognize_face

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Recognize a face.")
    parser.add_argument("image_path", type=str, help="Path to the image.")
    args = parser.parse_args()

    name = recognize_face(args.image_path)
    print(f"Recognized: {name}")