# -*- coding: utf-8 -*-
"""run_enrollment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nVsCtltcrFCdV4smdc8d-rISAXsC-nzq
"""

import argparse
from face_recognition.enrollment import enroll_face

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Enroll a face.")
    parser.add_argument("image_path", type=str, help="Path to the image.")
    parser.add_argument("name", type=str, help="Name of the person.")
    args = parser.parse_args()

    enroll_face(args.image_path, args.name)