# -*- coding: utf-8 -*-
"""webcam_recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pphZgI3QCDRHq0Lt-bxCU_uD87e-P0nf
"""

import cv2
from face_recognition.recognition import recognize_face

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    cv2.imwrite("temp.jpg", frame)
    name = recognize_face("temp.jpg")

    cv2.putText(frame, f"Name: {name}", (20, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow("Webcam Recognition", frame)

    if cv2.waitKey(1) & 0xFF == ord("q"):
        break

cap.release()
cv2.destroyAllWindows()