# -*- coding: utf-8 -*-
"""enrollment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDxqEY2JJsuDxU5BOjWDgFhe3Qtl76fE
"""

import cv2
import json
import os
import numpy as np
from .utils import load_database, save_database


def enroll_face(image_path, name):
    # Load the image
    image = cv2.imread(image_path)
    if image is None:
        print(f"Error: Unable to load image at {image_path}")
        return

    # Convert the image to RGB
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Find face encodings
    from face_recognition import face_locations, face_encodings
    face_locations = face_locations(image_rgb)
    face_encodings = face_encodings(image_rgb, face_locations)

    if len(face_encodings) == 0:
        print("No face found in the image.")
        return

    # Get the first face encoding
    face_encoding = face_encodings[0]

    # Load or initialize the database
    database = load_database()

    # Add the face encoding
    database[name] = face_encoding.tolist()

    # Save the updated database
    save_database(database)
    print(f"Face for {name} enrolled successfully.")