# -*- coding: utf-8 -*-
"""recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8IoHyP6IoQ1b0Ze8mxRE6_nGRavLAa0
"""

import cv2
import numpy as np
import json
from scipy.spatial.distance import cosine
from .utils import load_database


def recognize_face(image_path):
    # Load the image
    image = cv2.imread(image_path)
    if image is None:
        print(f"Error: Unable to load image at {image_path}")
        return "Error: Image not found"

    # Convert the image to RGB
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Find face encodings
    from face_recognition import face_locations, face_encodings
    face_locations = face_locations(image_rgb)
    face_encodings = face_encodings(image_rgb, face_locations)

    if len(face_encodings) == 0:
        print("No face detected.")
        return "No face detected"

    # Get the first face encoding
    face_encoding = face_encodings[0]

    # Load the database
    database = load_database()

    # Perform recognition
    min_distance = float("inf")
    recognized_name = "Unknown"

    for name, stored_encoding in database.items():
        stored_encoding = np.array(stored_encoding)
        distance = cosine(face_encoding, stored_encoding)

        if distance < min_distance:
            min_distance = distance
            recognized_name = name

    return recognized_name